//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSC_APP_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSC_APP_USER()
        {
            this.RZ_ACTION_PLAN_DTL = new HashSet<RZ_ACTION_PLAN_DTL>();
            this.RZ_ACTION_PLAN_DTL1 = new HashSet<RZ_ACTION_PLAN_DTL>();
            this.MTRC_USER_APP_ROLES = new HashSet<MTRC_USER_APP_ROLES>();
            this.RZ_BLDG_AUTHORIZATION = new HashSet<RZ_BLDG_AUTHORIZATION>();
        }
    
        public int app_user_id { get; set; }
        public Nullable<int> dsc_emp_id { get; set; }
        public string app_user_sso_id { get; set; }
        public string app_user_sso_system { get; set; }
        public string app_user_email_addr { get; set; }
        public string app_user_full_name { get; set; }
        public string app_user_disabled_yn { get; set; }
        public Nullable<System.DateTime> app_user_disabled_on_dtm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RZ_ACTION_PLAN_DTL> RZ_ACTION_PLAN_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RZ_ACTION_PLAN_DTL> RZ_ACTION_PLAN_DTL1 { get; set; }
        public virtual DSC_EMPLOYEE DSC_EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTRC_USER_APP_ROLES> MTRC_USER_APP_ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RZ_BLDG_AUTHORIZATION> RZ_BLDG_AUTHORIZATION { get; set; }
    }
}
