//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTRC_MPBG
    {
        public int mpbg_id { get; set; }
        public short dsc_mtrc_lc_bldg_id { get; set; }
        public int mtrc_period_id { get; set; }
        public short prod_id { get; set; }
        public Nullable<decimal> mpbg_less_val { get; set; }
        public Nullable<decimal> mpbg_less_eq_val { get; set; }
        public Nullable<decimal> mpbg_greater_val { get; set; }
        public Nullable<decimal> mpbg_greater_eq_val { get; set; }
        public string mpbg_equal_val { get; set; }
        public int mpbg_score { get; set; }
        public string mpbg_display_text { get; set; }
        public System.DateTime mpbg_start_eff_dtm { get; set; }
        public System.DateTime mpbg_end_eff_dtm { get; set; }
    
        public virtual DSC_MTRC_LC_BLDG DSC_MTRC_LC_BLDG { get; set; }
        public virtual MTRC_METRIC_PERIOD MTRC_METRIC_PERIOD { get; set; }
        public virtual MTRC_PRODUCT MTRC_PRODUCT { get; set; }
    }
}
