//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTRC_MP_REASON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MTRC_MP_REASON()
        {
            this.MTRC_MPV_REASONS = new HashSet<MTRC_MPV_REASONS>();
        }
    
        public int mpr_id { get; set; }
        public int mtrc_period_id { get; set; }
        public string mpr_display_text { get; set; }
        public Nullable<short> mpr_display_order { get; set; }
        public string mpr_desc { get; set; }
        public string mpr_std_yn { get; set; }
        public System.DateTime mpr_added_on_dtm { get; set; }
        public string mpr_added_by_uid { get; set; }
        public Nullable<System.DateTime> mpr_stdized_on_dtm { get; set; }
        public string mpr_stdized_by_uid { get; set; }
    
        public virtual MTRC_METRIC_PERIOD MTRC_METRIC_PERIOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTRC_MPV_REASONS> MTRC_MPV_REASONS { get; set; }
    }
}
