//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTRC_MPV_REASONS
    {
        public int mpvr_id { get; set; }
        public long mtrc_period_val_id { get; set; }
        public int mpr_id { get; set; }
        public System.DateTime mpvr_created_on_dtm { get; set; }
        public string mpvr_created_by_uid { get; set; }
        public Nullable<System.DateTime> mpvr_last_updt_on_dtm { get; set; }
        public string mpvr_last_updt_by_uid { get; set; }
        public string mpvr_comment { get; set; }
    
        public virtual MTRC_METRIC_PERIOD_VALUE MTRC_METRIC_PERIOD_VALUE { get; set; }
        public virtual MTRC_MP_REASON MTRC_MP_REASON { get; set; }
    }
}
