//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTRC_APP_ROLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MTRC_APP_ROLE()
        {
            this.MTRC_USER_APP_ROLES = new HashSet<MTRC_USER_APP_ROLES>();
        }
    
        public int mar_id { get; set; }
        public short prod_id { get; set; }
        public string mar_name { get; set; }
        public string mar_desc { get; set; }
        public string mar_req_bldg_auth { get; set; }
        public string mar_req_mtrc_mgmt_auth { get; set; }
        public System.DateTime mar_eff_start_dt { get; set; }
        public System.DateTime mar_eff_end_dt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTRC_USER_APP_ROLES> MTRC_USER_APP_ROLES { get; set; }
    }
}
