//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTRC_METRIC_PERIOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MTRC_METRIC_PERIOD()
        {
            this.MTRC_BLDG_MTRC_PERIOD = new HashSet<MTRC_BLDG_MTRC_PERIOD>();
            this.MTRC_METRIC_HIERARCHY = new HashSet<MTRC_METRIC_HIERARCHY>();
            this.MTRC_METRIC_HIERARCHY1 = new HashSet<MTRC_METRIC_HIERARCHY>();
            this.MTRC_METRIC_PERIOD_VALUE = new HashSet<MTRC_METRIC_PERIOD_VALUE>();
            this.MTRC_METRIC_PRODUCTS = new HashSet<MTRC_METRIC_PRODUCTS>();
            this.RZ_MTRC_PERIOD_STATUS = new HashSet<RZ_MTRC_PERIOD_STATUS>();
            this.MTRC_MPG = new HashSet<MTRC_MPG>();
            this.MTRC_MPBG = new HashSet<MTRC_MPBG>();
            this.MTRC_MP_REASON = new HashSet<MTRC_MP_REASON>();
            this.MTRC_MGMT_AUTH_NEW = new HashSet<MTRC_MGMT_AUTH_NEW>();
        }
    
        public int mtrc_period_id { get; set; }
        public int mtrc_id { get; set; }
        public short tpt_id { get; set; }
        public string mtrc_period_name { get; set; }
        public string mtrc_period_token { get; set; }
        public string mtrc_period_desc { get; set; }
        public string mtrc_period_calc_yn { get; set; }
        public Nullable<decimal> mtrc_period_min_val { get; set; }
        public Nullable<decimal> mtrc_period_max_val { get; set; }
        public Nullable<short> mtrc_period_max_dec_places { get; set; }
        public Nullable<short> mtrc_period_max_str_size { get; set; }
        public string mtrc_period_na_allow_yn { get; set; }
        public string mtrc_period_can_import_yn { get; set; }
        public string mtrc_period_is_auto_yn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTRC_BLDG_MTRC_PERIOD> MTRC_BLDG_MTRC_PERIOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTRC_METRIC_HIERARCHY> MTRC_METRIC_HIERARCHY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTRC_METRIC_HIERARCHY> MTRC_METRIC_HIERARCHY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTRC_METRIC_PERIOD_VALUE> MTRC_METRIC_PERIOD_VALUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTRC_METRIC_PRODUCTS> MTRC_METRIC_PRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RZ_MTRC_PERIOD_STATUS> RZ_MTRC_PERIOD_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTRC_MPG> MTRC_MPG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTRC_MPBG> MTRC_MPBG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTRC_MP_REASON> MTRC_MP_REASON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTRC_MGMT_AUTH_NEW> MTRC_MGMT_AUTH_NEW { get; set; }
    }
}
