//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTRC_USER_APP_ROLES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MTRC_USER_APP_ROLES()
        {
            this.MTRC_MGMT_AUTH_NEW = new HashSet<MTRC_MGMT_AUTH_NEW>();
        }
    
        public int muar_id { get; set; }
        public int app_user_id { get; set; }
        public int mar_id { get; set; }
        public System.DateTime muar_eff_start_dt { get; set; }
        public System.DateTime muar_eff_end_dt { get; set; }
    
        public virtual DSC_APP_USER DSC_APP_USER { get; set; }
        public virtual MTRC_APP_ROLE MTRC_APP_ROLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTRC_MGMT_AUTH_NEW> MTRC_MGMT_AUTH_NEW { get; set; }
    }
}
