//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTRC_MGMT_AUTH_NEW
    {
        public int mma_id { get; set; }
        public int muar_id { get; set; }
        public int mtrc_period_id { get; set; }
        public System.DateTime mma_eff_start_date { get; set; }
        public System.DateTime mma_eff_end_date { get; set; }
    
        public virtual MTRC_METRIC_PERIOD MTRC_METRIC_PERIOD { get; set; }
        public virtual MTRC_USER_APP_ROLES MTRC_USER_APP_ROLES { get; set; }
    }
}
