//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RZ_ACTION_PLAN_DTL
    {
        public int rz_apd_id { get; set; }
        public int rz_bapm_id { get; set; }
        public int rz_apd_subm_app_user_id { get; set; }
        public Nullable<int> rz_apd_revw_app_user_id { get; set; }
        public short rz_apd_ap_ver { get; set; }
        public System.DateTime rz_apd_ap_created_on_dtm { get; set; }
        public Nullable<System.DateTime> rz_apd_ap_last_saved_on_dtm { get; set; }
        public Nullable<System.DateTime> rz_apd_ap_submitted_on_dtm { get; set; }
        public string rz_apd_ap_status { get; set; }
        public Nullable<System.DateTime> rz_apd_ap_stat_upd_on_dtm { get; set; }
        public string rz_apd_ap_text { get; set; }
        public string rz_apd_ap_review_text { get; set; }
    
        public virtual DSC_APP_USER DSC_APP_USER { get; set; }
        public virtual DSC_APP_USER DSC_APP_USER1 { get; set; }
        public virtual RZ_BAP_METRICS RZ_BAP_METRICS { get; set; }
    }
}
