//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RZ_BAP_METRICS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RZ_BAP_METRICS()
        {
            this.RZ_ACTION_PLAN_DTL = new HashSet<RZ_ACTION_PLAN_DTL>();
        }
    
        public int rz_bapm_id { get; set; }
        public int rz_bap_id { get; set; }
        public long mtrc_period_val_id { get; set; }
        public string rz_bapm_status { get; set; }
        public Nullable<System.DateTime> rz_bapm_status_updt_dtm { get; set; }
        public System.DateTime rz_bapm_created_on_dtm { get; set; }
        public Nullable<System.DateTime> rz_bapm_ntfy_dtm { get; set; }
        public Nullable<System.DateTime> rz_bapm_approved_on_dtm { get; set; }
    
        public virtual MTRC_METRIC_PERIOD_VALUE MTRC_METRIC_PERIOD_VALUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RZ_ACTION_PLAN_DTL> RZ_ACTION_PLAN_DTL { get; set; }
        public virtual RZ_BLDG_ACTION_PLAN RZ_BLDG_ACTION_PLAN { get; set; }
    }
}
