//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RZ_BLDG_AUTHORIZATION
    {
        public int rzba_id { get; set; }
        public short dsc_mtrc_lc_bldg_id { get; set; }
        public Nullable<int> app_user_id { get; set; }
    
        public virtual DSC_APP_USER DSC_APP_USER { get; set; }
        public virtual DSC_MTRC_LC_BLDG DSC_MTRC_LC_BLDG { get; set; }
    }
}
