//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RZ_MTRC_PERIOD_STATUS
    {
        public int rz_mps_id { get; set; }
        public int tm_period_id { get; set; }
        public int mtrc_period_id { get; set; }
        public string rz_mps_status { get; set; }
        public Nullable<System.DateTime> rz_mps_opened_on_dtm { get; set; }
        public Nullable<System.DateTime> rz_mps_closed_on_dtm { get; set; }
        public string rz_mps_closed_by_usr_id { get; set; }
    
        public virtual MTRC_METRIC_PERIOD MTRC_METRIC_PERIOD { get; set; }
        public virtual MTRC_TM_PERIODS MTRC_TM_PERIODS { get; set; }
    }
}
